services:
  store_manager_app:
    container_name: store_manager_app
    build: .
    volumes:
      - .:/app
    depends_on:
      - mysql
      - mongo
    stdin_open: true
    tty: true  
    networks:
      - labo430-labo1-network

  mysql:
    container_name: mysql
    image: mysql:8
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - labo430-labo1-network

  mongo:
    container_name: mongo-db
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
    networks:
      - labo430-labo1-network

volumes:
  mongo-data:
networks:
  labo430-labo1-network:
    driver: bridge